import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      id: "1",
      userName: "shernof",
      email: "shernof@gmail.com",
      name: "Sherwin",
      joined: new Date(),
      isAdmin: true,
      password: bcrypt.hashSync("test"),
    },
    {
      id: 2,
      userName: "jedi",
      name: "Jedidiah",
      email: "jedi@gmail.com",
      password: bcrypt.hashSync("test1"),
      joined: new Date(),
      isAdmin: false,
    },
    {
      id: 3,
      userName: "angie",
      name: "Angelyn",
      email: "angie@gmail.com",
      password: bcrypt.hashSync("test2"),
      joined: new Date(),
      isAdmin: false,
    },
  ],
  churchEvents: [
    {
      eventNumber: 15,
      eventTitle: "Filipino Fiesta 2023",
      pictures: [
        {url:"../fiesta/1.jpeg"},
        {url:"../fiesta/2.jpeg"},
        {url:"../fiesta/3.jpeg"},
        {url:"../fiesta/4.jpeg"},
        {url:"../fiesta/5.jpeg"},
        {url:"../fiesta/6.jpeg"},
        {url:"../fiesta/7.jpeg"},
        {url:"../fiesta/8.jpeg"},
        {url:"../fiesta/9.jpeg"},
        {url:"../fiesta/10.jpeg"},
        {url:"../fiesta/11.jpeg"},
        {url:"../fiesta/12.jpeg"},
        {url:"../fiesta/13.jpeg"},
        {url:"../fiesta/14.jpeg"},
        {url:"../fiesta/15.jpeg"},
        {url:"../fiesta/16.jpeg"},
        {url:"../fiesta/17.jpeg"},
        {url:"../fiesta/18.jpeg"},
      ],
    },
    {
      eventNumber: 16,
      eventTitle: "Baptism 2023 Year Celebration 2022",
      pictures: [
        {url:"../wb/9.jpg"},
        {url:"../wb/7.jpg"},
        {url:"../wb/8.jpg"},
        {url:"../wb/6.jpg"},
        {url:"../wb/10.jpg"},
      ],
    },
    {
      eventNumber: 17,
      eventTitle: "Mens Fellowship",
      pictures: [
        {url:"../mf/10.jpg"},
        {url:"../mf/7.jpg"},
        {url:"../mf/8.jpg"},
        {url:"../mf/9.jpg"},
        {url:"../mf/6.jpg"},
        {url:"../mf/5.jpg"},
        {url:"../mf/4.jpg"},
        {url:"../mf/2.jpg"},
        {url:"../mf/1.jpg"},
      ],
    },
    {
      eventNumber: 18,
      eventTitle: "Ladies Ministry",
      pictures: [
        {url:"../lm/11.jpg"},
        {url:"../lm/12.jpg"},
        {url:"../lm/13.jpg"},
        {url:"../lm/18.jpg"},
        {url:"../lm/19.jpg"},
        {url:"../lm/20.jpg"},

        {url:"../lm/22.jpg"},
        {url:"../lm/23.jpg"},
        {url:"../lm/24.jpg"},
        {url:"../lm/25.jpg"},
        {url:"../lm/26.jpg"},
        {url:"../lm/27.png"},
        {url:"../lm/28.png"},
      ],
    },
  ],
  testimonials: [
    {
      testimonialNumber: 1,
      testimony: "Let's worship Jesus our Lord",
      name: "Jedi",
    },
  ],
};
export default data;
